function:
  handler: queue_injestor.queue_injestor.injest
  name: ${self:custom.deployStage}-${self:service}-injestor
  role: injestorRole
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.deployStage}
    APP_NAME: ${self:custom.appName}
    TASK_NAME: ${self:custom.pluginName}
  layers:
    - ${ssm:/${self:custom.appName}/${self:custom.ssmSourceStage}/lambda/layer/utils, ssm:/${self:custom.appName}/dev/lambda/layer/utils}
  events:
    - sqs:
        arn: ${ssm:/${self:custom.appName}/${self:custom.deployStage}/analytics/elastic/injest_queue/arn}
        batchSize: 1
        enabled: true

role:
  Type: AWS::IAM::Role
  Properties:
    Path:
      # Not allowed '-' characters in a path
      Fn::Join:
        - ""
        - Fn::Split:
            - "-"
            - /${self:custom.appName}/${self:custom.deployStage}/${self:service}/analytics/elastic/injestor/
    RoleName: ${self:custom.deployStage}-${self:service}-elastic-injestor
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: ${self:custom.deployStage}-${self:service}-elastic-injestor
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:ReceiveMessage
                - sqs:GetQueueAttributes
              Resource: ${ssm:/${self:custom.appName}/${self:custom.deployStage}/analytics/elastic/injest_queue/arn}
            - Effect: Allow
              Action:
                - ssm:GetParameters
              Resource: 
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:ssm'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'parameter/${self:custom.appName}/${self:custom.deployStage}/*'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:ssm'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'parameter/${self:custom.appName}/${self:custom.ssmSourceStage}/*'   
              