function:
  handler: queue_ingestor.queue_ingestor.ingest
  name: ${self:custom.deployStage}-${self:service}-ingestor
  role: ingestorRole
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.deployStage}
    APP_NAME: ${self:custom.appName}
    TASK_NAME: ${self:custom.pluginName}
  layers:
    - ${ssm:/${self:custom.appName}/${self:custom.ssmSourceStage}/lambda/layer/utils, ssm:/${self:custom.appName}/dev/lambda/layer/utils}
  events:
    - sqs:
        arn: ${ssm:/${self:custom.appName}/${self:custom.deployStage}/analytics/elastic/ingest_queue/arn}
        batchSize: 1
        enabled: true

role:
  Type: AWS::IAM::Role
  Properties:
    Path:
      # Not allowed "-" characters in a path
      Fn::Join:
        - ""
        - Fn::Split:
            - "-"
            - /${self:custom.appName}/${self:custom.deployStage}/${self:service}/analytics/elastic/ingestor/
    RoleName: ${self:custom.deployStage}-${self:service}-elastic-ingestor
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: ${self:custom.deployStage}-${self:service}-elastic-ingestor
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:CreateLogGroup
              Resource: "*"
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:ReceiveMessage
                - sqs:GetQueueAttributes
              Resource: ${ssm:/${self:custom.appName}/${self:custom.deployStage}/analytics/elastic/ingest_queue/arn}
            - Effect: Allow
              Action:
                - ssm:GetParameters
              Resource: 
                - "Fn::Join":
                    - ":"
                    - - "arn:aws:ssm"
                      - Ref: "AWS::Region"
                      - Ref: "AWS::AccountId"
                      - "parameter/${self:custom.appName}/${self:custom.deployStage}/*"
                - "Fn::Join":
                    - ":"
                    - - "arn:aws:ssm"
                      - Ref: "AWS::Region"
                      - Ref: "AWS::AccountId"
                      - "parameter/${self:custom.appName}/${self:custom.ssmSourceStage}/*"
            - Effect: Allow
              Action:
                - es:ESHttp*
              Resource: ${ssm:/${self:custom.appName}/${self:custom.deployStage}/analytics/elastic/es_endpoint/arn}/*

